// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ5O4gwarcHflXXlZycWqPxxih9d4k2EU',
    appId: '1:57000538605:web:e96caca1bb9510a1cb37e4',
    messagingSenderId: '57000538605',
    projectId: 'chatapptuto-fce3b',
    authDomain: 'chatapptuto-fce3b.firebaseapp.com',
    storageBucket: 'chatapptuto-fce3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAYhdbD9T-HxyFIQO1s--TWWghFO9keCI',
    appId: '1:57000538605:android:4bfdffd6353c5909cb37e4',
    messagingSenderId: '57000538605',
    projectId: 'chatapptuto-fce3b',
    storageBucket: 'chatapptuto-fce3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcIDexxLlSvt0PSaanZtNdr0oDwXtGN8E',
    appId: '1:57000538605:ios:3a0e0c8fb587ca4bcb37e4',
    messagingSenderId: '57000538605',
    projectId: 'chatapptuto-fce3b',
    storageBucket: 'chatapptuto-fce3b.appspot.com',
    iosBundleId: 'com.example.chatapptuto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcIDexxLlSvt0PSaanZtNdr0oDwXtGN8E',
    appId: '1:57000538605:ios:3a0e0c8fb587ca4bcb37e4',
    messagingSenderId: '57000538605',
    projectId: 'chatapptuto-fce3b',
    storageBucket: 'chatapptuto-fce3b.appspot.com',
    iosBundleId: 'com.example.chatapptuto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ5O4gwarcHflXXlZycWqPxxih9d4k2EU',
    appId: '1:57000538605:web:c506940977a150dfcb37e4',
    messagingSenderId: '57000538605',
    projectId: 'chatapptuto-fce3b',
    authDomain: 'chatapptuto-fce3b.firebaseapp.com',
    storageBucket: 'chatapptuto-fce3b.appspot.com',
  );

}